image: maven:3-jdk-11-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
   - .m2/repository/
   - target/jib-cache/

stages:
  - build
  - test
  - verify
  - package

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml

verify:
  stage: verify
  script:
  - mvn $MAVEN_CLI_OPTS dependency-check:check
  artifacts:
    paths:
    - target/dependency-check-report.html

package:
  stage: package
  script:
  - mvn $MAVEN_CLI_OPTS jib:build

