image: maven:3-jdk-11-slim

cache:
  paths:
    - ~/.m2

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/dependency-check-report.html