image: maven:3-jdk-11-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
   - .m2/repository/

stages:
  - build
  - test
  - verify
  - package

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml

verify:
  stage: verify
  allow_failure: true
  script:
  - mvn $MAVEN_CLI_OPTS dependency-check:check
  only:
  - master
  artifacts:
    paths:
    - target/dependency-check-report.html

package:
  stage: package
  script:
  - mvn $MAVEN_CLI_OPTS -Dquarkus.container-image.username=gitlab-ci-token -Dquarkus.container-image.password=$CI_JOB_TOKEN -Dquarkus.container-image.registry=$CI_REGISTRY -Dquarkus.container-image.group=$CI_PROJECT_NAMESPACE -Dquarkus.container-image.tag=build-$CI_PIPELINE_ID -Dquarkus.container-image.additional-tags=$CI_COMMIT_REF_SLUG -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true package
  only:
    - master
