apiVersion: v1
kind: Service
metadata:
  name: kampuni
spec:
  type: NodePort
  selector:
    app: kampuni
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kampuni-deployment
  labels:
    app: kampuni
    version: v0.1.1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kampuni
  template:
    metadata:
      labels:
        app: kampuni
    spec:
      containers:
      - name: kampuni
        image: magru/kampuni:v0.1.1
        ports:
        - containerPort: 8080
