apiVersion: v1
kind: Service
metadata:
  name: kampuni
spec:
  type: NodePort
  selector:
    app: kampuni
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kampuni-deployment
  labels:
    app: kampuni
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: kampuni
  template:
    metadata:
      labels:
        app: kampuni
    spec:
      containers:
      - name: kampuni
        image: kampuni:devel
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
